SEED: 42

DATASET:
  datadir: "dataset/data"
  transform: standard
  split: test 

DATALOADER:
  batch_size: 256
  shuffle: False

MODEL:
  name: vit_pretrained  # choose one in ['resnet50', 'resnet50_pretrained', 'vit', 'vit42', 'vit_pretrained']
  pyramid: True   # only works when 'resnet50_pretrained' is selected