EXPERIMENTS:
  EXP1:
    EXP_NAME: temp
    SEED: 42

    DATASET:
      url: "https://drive.google.com/drive/folders/1wEnwMeJoQZwJhI7oBRah3I8QX-FpLMYD"
      datadir: "dataset/data"
      val_ratio: 0.1

    DATALOADER:
      batch_size: 256
      shuffle: True

    TRAIN:    
      transform: softcrop
      freeze: False
      max_step: 14400
      eval_interval: 40 
      use_wandb: False
    
    MODEL:
      model_name: "resnet50"    # choose one in ['resnet50', 'resnet50_pretrained', 'vit', 'vit42', 'vit_pretrained']
      pyramid: True    # only works when 'resnet50_pretrained' is selected

    VAL:
      transform: null

    OPTIMIZER:
      name: AdamW   # only supported
      lr: 0.0001
      betas: (0.9, 0.999)
      weight_decay: 0.0001

    SCHEDULER:
      scheduler: True
      cycle: 5

    LOG:
      log_interval: 20

    RESULT:
      savedir: "./results"